# Dockerfile.api
FROM python:3.10-slim
WORKDIR /app
COPY todolist-api/requirements.txt todolist-api/api.py todolist-api/.flaskenv todolist-api/todolist.db ./
RUN pip install -r requirements.txt
EXPOSE 8080
CMD ["flask","run","--host=0.0.0.0", "--port=8080"] 